export type ProjectType = {
  id: string;
  title?: string;
  name?: string;
  shortDescription?: string;
  tagline?: string;
  description?: string;
  excerpt?: string;
  image?: string;
  mockupImage?: string;
  imagePath?: string;
  bannerGradient?: string;
  tags?: string[];
  timeline?: string;
  role?: string;
  techStack?: Array<{ name: string; iconId: string; category?: string }>;
  status: string;
  projectType?: string;
  technologies?: string[];
  videoUrl?: string;
  liveUrl?: string;
  link?: string;
  demoLink?: string;
  githubUrl?: string;
  githubLink?: string;
  overview?: string;
  whatUsersCanDo?: string[];
  whyIBuiltThis?: string;
  features?: string[];
  impact?: string;
  futurePlans?: string[];
};
