import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { Analytics } from "@vercel/analytics/next";

import FooterBlur from "@/components/Footer/FooterBlur";
import NavBar from "@/components/Navbar/NavBar";
import PageTransition from "@/components/PageTransition/PageTransition";
import { ThemeProvider } from "@/hooks/ThemeProvider";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL(
    process.env.NEXT_PUBLIC_BASE_URL || "http://localhost:3000"
  ),
  title: "Sahil Mishra",
  description: "Generated by create next app",
  icons: {
    icon: "/cropped_circle_image.png",
  },
  openGraph: {
    images: [
      {
        url: "/og_image.png",
        width: 1200,
        height: 630,
        alt: "Open Graph Image",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    images: ["/og_image.png"],
  },
};

// Script to prevent flash of incorrect theme
const themeInitScript = `
  (function() {
    try {
      const savedTheme = localStorage.getItem('theme');
      const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
      if (savedTheme === 'light') {
        document.documentElement.classList.remove('dark');
      } else {
        document.documentElement.classList.add('dark');
      }
    } catch (e) {}
  })();
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
        <link rel="preload" href="/Logo.webp" as="image" type="image/webp" />
        <link rel="preload" href="/x.webp" as="image" type="image/webp" />
        <link
          rel="preload"
          href="/linkedin.webp"
          as="image"
          type="image/webp"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <ThemeProvider>
          <NavBar />
          <PageTransition>
            {children}
          </PageTransition>
          <FooterBlur />
        </ThemeProvider>
        <Analytics />
      </body>
    </html>
  );
}
